## school-tagging --> an educative Student / Classroom 
##    Response Systems designed to help teaching and merge into 
##    academic research.
##    Copyright (C) 2014  Stefano Merlo, Federico Sangati, Giovanni Moretti.
## This program comes with ABSOLUTELY NO WARRANTY.
## This is free software, and you are welcome to redistribute it 
## under certain conditions (i.e. attribution); for details refer 
##     to 'LICENSE.txt'.

application: school-tagging
version: 8a
runtime: python27
api_version: 1
threadsafe: yes
env_variables:
    DEV_WORKFLOW_STATUS: "productio" #production or development

handlers:
- url: /admin/.*
  script: main.app
  login: admin
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /lists
  static_dir: lists
  application_readable: true

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

inbound_services:
 - channel_presence
